<?php

namespace ProcessWire;

class BlocksAccordion extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Accordion Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'plus',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.0.17',
      'pg_name' => 'pg_accordion',
      'pg_label' => 'Accordion',
      'pg_description' => 'Renders a collapsible accordion component with expandable/collapsible items. Each item displays a title with expand/collapse icons and content that reveals when clicked.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);

    $f = $b->createField('pg_accordion_numbering', 'FieldtypeOptions', $blockName);
    $f->label = 'Numbering';
    $f->inputfieldClass = 'InputfieldSelect';
    $f->collapsed = 0;
    $f->required = 1;
    $f->columnWidth = 99;
    $f->set('initValue', 'none');
    $f->save();
    $options = 'none|None
1|1,2,3
01|01,02,03
001|001,002,003
(1)|(1),(2),(3)
(01)|(01),(02),(03)
(001)|(001),(002),(003)
[1]|[1],[2],[3]
[01]|[01],[02],[03]
[001]|[001],[002],[003]';
    $this->manager = new \ProcessWire\SelectableOptionManager();
    $this->manager->deleteAllOptionsForField($f);
    $this->manager->setOptionsString($f, $options, false);
    $f->save();
    //set allowed templates for children if not defined already
    // if (!count($t->childTemplates) && $this->templates->get('pg_editor')->id && $this->templates->get('pg_group')->id) {
    //   $t->childTemplates = [$this->templates->get('pg_editor')->id, $this->templates->get('pg_group')->id];
    //   $t->save();
    // }

    //enable title field for inline editing (title is used for accordion header)
    $f = $this->fields->get('title');
    $this->modules->get('PageGridBlocks')->enableInlineEdit($f);
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    //install module
    $this->modules->get('PageGridBlocks')->downloadModule('InputfieldTinyMCE');
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
