<?php namespace ProcessWire;

class BlocksText extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Text Block (line breaks + links via TinyMCE)',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'author' => 'Jan Ploch',
      'icon' => 'font',
      'autoload' => 'template=admin',
      'installs' => array('InputfieldTinyMCE'),
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.8.0'
    ];
  }

  public function getBlockName() {
    return array(
      'name' => 'pg_text',
      'label' => 'Text',
    );
  }

  //function to create block
  public function createBlock() {

    //make sure module is available
    if (!$this->modules->isInstalled('InputfieldTinyMCE')) {
      $this->modules->install('InputfieldTinyMCE');
      $this->modules->refresh();
    }

    // enable json module settings
    $data = $this->modules->getConfig('InputfieldTinyMCE');
    // $data['optionals'] = array('settingsJSON');
    if(!array_key_exists('optionals', $data)) $data['optionals'] = [];
    array_push($data['optionals'], "settingsJSON");
    $this->modules->saveConfig('InputfieldTinyMCE', $data);
    // END enable json module settings

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getBlockName()['name'];
    $blockLabel = $this->getBlockName()['label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $b->createTemplate($blockName, $blockLabel, $blockIcon);

    $f = $b->createField($blockName, 'FieldtypeTextarea', $blockName);
    $f->label = $blockLabel;
    $f->inputfieldClass = 'InputfieldTinyMCE';
    $f->contentType = 1;
    $f->htmlOptions = array(0 => 2);
    $f->inlineMode = 1;
    $f->features = array(0 => 'toolbar', 1 => 'stickybars', 2 => 'spellcheck', 3 => 'purifier', 4 => 'pasteFilter');
    $f->toolbar = 'pwlink';
    $f->plugins = array(0 => 'link', 1 => 'lists', 2 => 'pwlink');
    $f->settingsJSON = '{"forced_root_block": "div", "newline_behavior": "linebreak", "valid_elements": "a[href|target=_blank],br"}';
    $f->save();

    $this->modules->get('PageGridBlocks')->enableInlineEdit($f);
    $this->modules->get('PageGridBlocks')->setPlaceholderText($f, 'Click twice to edit this text');
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    //install module
    $this->modules->get('PageGridBlocks')->downloadModule('InputfieldTinyMCE');
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getBlockName()['name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
