<?php

namespace ProcessWire;

class BlocksReference extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Reference Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'link',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.1.1',
      'pg_name' => 'pg_reference',
      'pg_label' => 'Reference',
      'pg_description' => 'Renders a referenced page block by displaying another page\'s content. Acts as an include/embed mechanism for reusing page content.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();

    $f = $b->createField($blockName, 'FieldtypePage', $blockName);
    $f->label = $blockLabel;
    $f->inputfield = 'InputfieldPageListSelect';
    $f->derefAsPage = 1;
    $f->parent_id = 1;
    $f->labelFieldName = 'title';
    $f->contentType = 1;
    $f->save();
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
