<?php

namespace ProcessWire;

class BlocksSequenz extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Image Sequenz',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'film',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.1.2',
      'pg_name' => 'pg_sequenz',
      'pg_label' => 'Sequenz',
      'pg_description' => 'Renders an image sequence animation on HTML5 canvas. Creates flipbook-style animations by cycling through multiple image files.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();

    $f = $b->createField($blockName, 'FieldtypeImage', $blockName);
    $f->label = $blockLabel;
    $f->extensions = 'gif jpg jpeg png';
    $f->maxFiles = 0;
    $f->outputFormat = 0;
    $f->overwrite = 1;
    $f->save();
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
