<?php

namespace ProcessWire;

class BlocksTextPlain extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Plain Text Block (no HTML)',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'i-cursor',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.7.2',
      'pg_name' => 'pg_text_plain',
      'pg_label' => 'Plain Text',
      'pg_description' => 'A text-only block that automatically strips all HTML tags to ensure clean, unformatted output.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();

    $f = $b->createField($blockName, 'FieldtypeTextarea', $blockName);
    $f->label = $blockLabel;
    $f->inputfieldClass = 'InputfieldTextarea';
    $f->contentType = 1;
    $f->stripTags = 1;
    $f->textformatters = array(0 => 'TextformatterEntities');
    $f->save();

    $this->modules->get('PageGridBlocks')->enableInlineEdit($f);
    $this->modules->get('PageGridBlocks')->setPlaceholderText($f, 'Click twice to edit this text');
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
