<?php namespace ProcessWire;

class BlocksSequenz extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Image Sequenz',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'author' => 'Jan Ploch',
      'icon' => 'film',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => 001
    ];
  }

  public function getBlockName() {
    return array(
      'name' => 'pg_sequenz',
      'label' => 'Sequenz',
    );
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getBlockName()['name'];
    $blockLabel = $this->getBlockName()['label'];
    $blockIcon = $this->getModuleInfo()['icon'];
    $folderName = $this->className();

    $b->createTemplate($blockName, $blockLabel, $blockIcon, $folderName);

    $f = $b->createField($blockName, 'FieldtypeImage', $blockName);
    $f->label = $blockLabel;
    $f->extensions = 'gif jpg jpeg png';
    $f->maxFiles = 0;
    $f->outputFormat = 0;
    $f->overwrite = 1;
    $f->save();
    
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getBlockName()['name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
  
}