<?php

namespace ProcessWire;

class BlocksGalleryVideo extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Gallery Video Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'video-camera',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.1.4',
      'pg_name' => 'pg_gallery_video',
      'pg_label' => 'Gallery Video',
      'pg_description' => 'Renders a video in a PhotoSwipe gallery with playable preview. Includes thumbnail/poster support and video options configuration.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();

    $f = $b->createField($blockName, 'FieldtypeFile', $blockName);
    $f->label = $blockLabel;
    $f->extensions = 'mp4';
    $f->maxFiles = 1;
    $f->outputFormat = 0;
    $f->save();

    $f = $b->createField($blockName . '_poster', 'FieldtypeImage', $blockName);
    $f->label = 'Preview Image';
    $f->extensions = 'gif jpg jpeg png';
    $f->maxFiles = 1;
    $f->save();

    $f = $b->createField($blockName . '_options', 'FieldtypeText', $blockName);
    $f->label = 'Options';
    $f->notes = 'example: autoplay muted loop';
    $f->save();
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
