<?php

namespace ProcessWire;

class BlocksSpacer extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Spacer Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'arrows-h',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.1.1',
      'pg_name' => 'pg_spacer',
      'pg_label' => 'Spacer',
      'pg_description' => 'Renders an empty spacing block for layout control. Used to add vertical spacing between blocks without content.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
