<?php

namespace ProcessWire;

class BlocksGallery extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Gallery Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'author' => 'Jan Ploch',
      'icon' => 'camera-retro',
      'autoload' => 'template=admin',
      'installs' => array('FileValidatorSvgSanitizer'),
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.1.0'
    ];
  }

  public function getBlockName() {
    return array(
      'name' => 'pg_gallery',
      'label' => 'Gallery',
    );
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getBlockName()['name'];
    $blockLabel = $this->getBlockName()['label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $b->createTemplate($blockName, $blockLabel, $blockIcon);

    $f = $b->createField($blockName, 'FieldtypeImage', $blockName);
    $f->label = $blockLabel;
    $f->extensions = 'gif jpg jpeg png svg';
    $f->maxFiles = 1;
    $f->outputFormat = 2;
    $f->save();
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    //install module
    $this->modules->get('PageGridBlocks')->downloadModule('FileValidatorSvgSanitizer');
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getBlockName()['name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
