<?php namespace ProcessWire;

class BlocksReference extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Reference Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'author' => 'Jan Ploch',
      'icon' => 'link',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => 001
    ];
  }

  public function getBlockName() {
    return array(
      'name' => 'pg_reference',
      'label' => 'Reference',
    );
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getBlockName()['name'];
    $blockLabel = $this->getBlockName()['label'];
    $blockIcon = $this->getModuleInfo()['icon'];
    $folderName = $this->className();

    $b->createTemplate($blockName, $blockLabel, $blockIcon, $folderName);

    $f = $b->createField($blockName, 'FieldtypePage', $blockName);
    $f->label = $blockLabel;
    $f->inputfield = 'InputfieldPageListSelect';
    $f->derefAsPage = 1;
    $f->parent_id = 1;
    $f->labelFieldName = 'title';
    $f->contentType = 1;
    $f->save();
  
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getBlockName()['name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
  
}