<?php

namespace ProcessWire;

class BlocksImage extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Image Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'author' => 'Jan Ploch',
      'icon' => 'file-image-o',
      'autoload' => 'template=admin',
      'installs' => array('FileValidatorSvgSanitizer'),
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.5.13'
    ];
  }

  public function getBlockName() {
    return array(
      'name' => 'pg_image',
      'label' => 'Image',
    );
  }

  //function to create block
  public function createBlock() {
    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getBlockName()['name'];
    $blockLabel = $this->getBlockName()['label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);

    $f = $b->createField($blockName, 'FieldtypeImage', $blockName);
    $f->label = $blockLabel;
    $f->extensions = 'gif jpg jpeg png svg';
    $f->maxFiles = 1;
    $f->outputFormat = 2;
    if (!$f->maxWidth) $f->maxWidth = 3000;
    if (!$f->maxHeight) $f->maxHeight = 3000;
    $f->save();

    $f = $b->createField($blockName . '_link', 'FieldtypePage', $blockName);
    $f->label = 'Link';
    $f->inputfield = 'InputfieldPageListSelect';
    $f->derefAsPage = 1;
    $f->parent_id = 1;
    $f->labelFieldName = 'title';
    $f->contentType = 1;
    $f->save();

    $f = $b->createField($blockName . '_link_external', 'FieldtypeText', $blockName);
    $f->label = 'External Link';
    $f->save();

    $f = $b->createField($blockName . '_ratio_fieldset', 'FieldtypeFieldsetOpen', $blockName);
    $f->label = 'Aspect Ratio';
    $f->description = "Enter a ratio, e.g. 16:9 if you want to crop the image, leave these fields blank to retain the original size.";
    $f->save();

    $f = $b->createField($blockName . '_ratio_width', 'FieldtypeInteger', $blockName);
    $f->label = 'Width';
    $f->inputType = 'number';
    $f->columnWidth = 50;
    $f->save();

    $f = $b->createField($blockName . '_ratio_height', 'FieldtypeInteger', $blockName);
    $f->label = 'Height';
    $f->inputType = 'number';
    $f->columnWidth = 50;
    $f->save();

    $f = $b->createField($blockName . '_ratio_fieldset_close', 'FieldtypeFieldsetClose', $blockName);
    $f->save();

    $f = $b->createField($blockName . '_caption', 'FieldtypeTextarea', $blockName);
    $f->label = 'Caption';
    $f->inputfieldClass = 'InputfieldTinyMCE';
    $f->contentType = 1;
    $f->htmlOptions = array(0 => 2);
    $f->inlineMode = 1;
    $f->features = array(0 => 'toolbar', 1 => 'stickybars', 2 => 'spellcheck', 3 => 'purifier', 4 => 'pasteFilter');
    $f->toolbar = 'styles bold italic pwlink hr bullist numlist table code';
    $f->plugins = array(0 => 'link', 1 => 'lists', 2 => 'pwlink');
    $f->settingsJSON = '';
    $f->toggles = [0 => 16]; // remove inline styles on save
    $f->save();

    $b->enableInlineEdit($f);
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    //install module
    $this->modules->get('PageGridBlocks')->downloadModule('FileValidatorSvgSanitizer');
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getBlockName()['name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
