<?php

namespace ProcessWire;

class BlocksGallery extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Gallery Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'camera-retro',
      'autoload' => 'template=admin',
      'installs' => array('FileValidatorSvgSanitizer'),
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.1.7',
      'pg_name' => 'pg_gallery',
      'pg_label' => 'Gallery',
      'pg_description' => 'Displays a single image in a PhotoSwipe-compatible gallery container. Supports responsive images with multiple size variants for optimal loading.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();

    $f = $b->createField($blockName, 'FieldtypeImage', $blockName);
    $f->label = $blockLabel;
    $f->extensions = 'gif jpg jpeg png svg';
    $f->maxFiles = 1;
    $f->outputFormat = 2;
    if (!$f->maxWidth) $f->maxWidth = 3000;
    if (!$f->maxHeight) $f->maxHeight = 3000;
    $f->save();
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    //install module
    $this->modules->get('PageGridBlocks')->downloadModule('FileValidatorSvgSanitizer');
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
