<?php namespace ProcessWire;

class BlocksMap extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Map Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'author' => 'Jan Ploch',
      'icon' => 'map',
      'autoload' => 'template=admin',
      'installs' => array('FieldtypeLeafletMapMarker'),
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.1.0'
    ];
  }

  public function getBlockName() {
    return array(
      'name' => 'pg_map',
      'label' => 'Map',
    );
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getBlockName()['name'];
    $blockLabel = $this->getBlockName()['label'];
    $blockIcon = $this->getModuleInfo()['icon'];
    
    $b->createTemplate($blockName, $blockLabel, $blockIcon);

    $f = $b->createField($blockName, 'FieldtypeLeafletMapMarker', $blockName);
    $f->label = $blockLabel;
    $f->defaultLat = '53.550341';
    $f->defaultLng = '10.000654';
    $f->defaultProvider = 'Stamen.Toner';
    $f->save();
    
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    //install module
    $this->modules->get('PageGridBlocks')->downloadModule('FieldtypeLeafletMapMarker');
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getBlockName()['name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
  
}