<?php

namespace ProcessWire;

class BlocksMarker extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Marker Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'map-pin',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.1.2',
      'pg_name' => 'pg_marker',
      'pg_label' => 'Marker',
      'pg_description' => 'Displays a numbered marker pin with label and content popup. Used for annotations and callouts on pages or maps.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();

    $f = $b->createField($blockName . '_label', 'FieldtypeText', $blockName);
    $f->textformatters = array(0 => 'TextformatterEntities');
    $f->label = 'Marker Label';
    $f->save();

    $f = $b->createField($blockName, 'FieldtypeTextarea', $blockName);
    $f->label = $blockLabel;
    $f->save();
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
