<?php

namespace ProcessWire;

class BlocksCode extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Custom Code Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'code',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.0.12',
      'pg_name' => 'pg_code',
      'pg_label' => 'Code',
      'pg_description' => 'Allows embedding of custom HTML, CSS, and JavaScript code. Provides a code block that executes frontend code while showing disabled preview in the backend editor.'
    ];
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();

    $f = $b->createField($blockName, 'FieldtypeTextarea', $blockName);
    $f->label = $blockLabel;
    $f->inputfieldClass = 'InputfieldTextarea';
    $f->contentType = 1;
    $f->stripTags = 0;
    $f->rows = 30;
    $f->textformatters = array();
    $f->save();
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
