<?php namespace ProcessWire;

class BlocksEditor extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Rich Text Editor Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'author' => 'Jan Ploch',
      'icon' => 'text-height',
      'autoload' => 'template=admin',
      'installs' => array('InputfieldTinyMCE'),
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.8.0'
    ];
  }

  public function getBlockName() {
    return array(
      'name' => 'pg_editor',
      'label' => 'Rich Text',
    );
  }

  //function to create block
  public function createBlock() {

    //make sure module is available
    if (!$this->modules->isInstalled('InputfieldTinyMCE')) {
      $this->modules->install('InputfieldTinyMCE');
      $this->modules->install('PageFrontEdit');
      $this->modules->refresh();
    }

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getBlockName()['name'];
    $blockLabel = $this->getBlockName()['label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $f = $b->createField($blockName, 'FieldtypeTextarea', $blockName);
    $f->inputfieldClass = 'InputfieldTinyMCE';
    $f->label = $blockLabel;
    $f->contentType = 1;
    $f->htmlOptions = array(0 => 2);
    $f->inlineMode = 1;
    $f->features = array(0 => 'toolbar', 1 => 'stickybars', 2 => 'spellcheck', 3 => 'purifier', 4 => 'pasteFilter');
    $f->save();

    $this->modules->get('PageGridBlocks')->enableInlineEdit($f);
    $this->modules->get('PageGridBlocks')->setPlaceholderText($f, 'Click twice to edit this text');
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->modules->get('PageGridBlocks')->downloadModule('InputfieldTinyMCE');
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getBlockName()['name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
