<?php

namespace ProcessWire;

class BlocksNavigation extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Navigation Block',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'author' => 'Jan Ploch',
      'icon' => 'bars',
      'autoload' => 'template=admin',
      'requires' => array('PageGridBlocks'),
      'installs' => array('FieldtypeRepeater'),
      'version' => '0.0.12.5'
    ];
  }

  public function getBlockName() {
    return array(
      'name' => 'pg_navigation',
      'label' => 'Navigation',
    );
  }

  //function to create block
  public function createBlock() {

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getBlockName()['name'];
    $blockLabel = $this->getBlockName()['label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    $b->createTemplate($blockName, $blockLabel, $blockIcon);

    $f = $b->createField($blockName . '_showHamburger', 'FieldtypeInteger', $blockName);
    $f->label = 'Mobile menu breakpoint';
    $f->description = 'Screen size in pixel, when the mobile menu icon should be shown instead of the menu links (Default: 640).';
    $f->placeholder = '640';
    $f->save();

    $f = $b->createField($blockName . '_link_label', 'FieldtypeText');
    $f->label = 'Label';
    $f->placeholder = $f->label;
    $f->hideFieldTitle = 1;
    $f->contentType = 1;
    $f->stripTags = 1;
    $f->textformatters = array(0 => 'TextformatterEntities');
    $f->save();

    $f = $b->createField($blockName . '_link', 'FieldtypeText');
    $f->label = 'URL';
    $f->placeholder = $f->label;
    $f->hideFieldTitle = 1;
    $f->contentType = 1;
    $f->stripTags = 1;
    $f->textformatters = array(0 => 'TextformatterEntities');
    $f->save();

    $f = $b->createRepeater($blockName . '_links', $blockName . '_link_label ' . $blockName . '_link', 'Links','', $blockName);
    $f->description = 'This block generates links to your published, non-hidden pages automatically. Optionally you can add more links here.';
    $f->repeaterTitle = '{pg_navigation_link_label}';
    $f->save();
    
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getBlockName()['name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
