<?php

namespace ProcessWire;

class BlocksText extends WireData implements Module {

  public static function getModuleInfo() {
    return [
      'title' => 'Text Block (line breaks + links via TinyMCE)',
      'summary' => 'Installs Template and Fields for a PageGrid Block',
      'href' => 'https://page-grid.com/docs/blocks/',
      'author' => 'Jan Ploch',
      'icon' => 'font',
      'autoload' => 'template=admin',
      'installs' => array('InputfieldTinyMCE'),
      'requires' => array('PageGridBlocks'),
      'version' => '0.0.10.4',
      'pg_name' => 'pg_text',
      'pg_label' => 'Text',
      'pg_description' => 'Renders rich text content with support for line breaks and links via TinyMCE. Similar to Editor but with simpler formatting options.'
    ];
  }

  //function to create block
  public function createBlock() {

    //make sure module is available
    if (!$this->modules->isInstalled('InputfieldTinyMCE')) {
      $this->modules->install('InputfieldTinyMCE');
      $this->modules->refresh();
    }

    $b = $this->modules->get('PageGridBlocks');
    $blockName = $this->getModuleInfo()['pg_name'];
    $blockLabel = $this->getModuleInfo()['pg_label'];
    $blockIcon = $this->getModuleInfo()['icon'];

    //enable editor json module settings
    $b->enableEditorSettings();

    $t = $b->createTemplate($blockName, $blockLabel, $blockIcon);
    $t->noChildren = 1;
    $t->save();

    $f = $b->createField($blockName, 'FieldtypeTextarea', $blockName);
    $f->label = $blockLabel;
    $f->inputfieldClass = 'InputfieldTinyMCE';
    $f->contentType = 1;
    $f->htmlOptions = array(0 => 2);
    $f->inlineMode = 1;
    $f->features = array(0 => 'toolbar', 1 => 'stickybars', 2 => 'spellcheck', 3 => 'purifier', 4 => 'pasteFilter');
    $f->toolbar = 'pwlink';
    $f->plugins = array(0 => 'link', 1 => 'lists', 2 => 'pwlink');
    $f->settingsJSON = '{"forced_root_block": "div", "newline_behavior": "linebreak", "valid_elements": "div,a[id|class|href|target],br"}';
    $f->toggles = [0 => 16]; // remove inline styles on save
    $f->save();

    $this->modules->get('PageGridBlocks')->enableInlineEdit($f);
    $this->modules->get('PageGridBlocks')->setPlaceholderText($f, 'Click twice to edit this text');
  }

  public function ___upgrade($fromVersion, $toVersion) {
    $this->createBlock();
  }

  public function ___install() {
    //install module
    $this->modules->get('PageGridBlocks')->downloadModule('InputfieldTinyMCE');
    $this->createBlock();
  }

  public function ___uninstall() {
    $blockName = $this->getModuleInfo()['pg_name'];
    $this->modules->get('PageGridBlocks')->removeBlock($blockName);
  }
}
